apiVersion: v1
kind: ConfigMap
metadata:
  name: lego-config
data:
  db_host: "mysql-d5b37567-o06c3efae.database.cloud.ovh.net"  # Update with your MySQL service name or external IP
  db_port: "20184"
  db_name: "lego"

