apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lego-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - lego-dashboard.essor.cloud
    - lego-admin.essor.cloud
    secretName: lego-tls-cert
  rules:
  - host: lego-dashboard.essor.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lego-streamlit
            port:
              number: 80
  - host: lego-admin.essor.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: lego-flask
            port:
              number: 80