apiVersion: v1
kind: Secret
metadata:
  name: lego-secrets
type: Opaque
stringData:
  db_user: "avnadmin"  # Update with your actual database user
  db_password: "QrfopezvMA67kC43X0TZ"  # Update with your actual database password

