apiVersion: v1
kind: Service
metadata:
  name: lego-streamlit
  labels:
    app: lego-apps
spec:
  type: LoadBalancer  # Change to NodePort or ClusterIP based on your cluster setup
  ports:
  - port: 80
    targetPort: 8501
    protocol: TCP
    name: streamlit
  selector:
    app: lego-apps
---
apiVersion: v1
kind: Service
metadata:
  name: lego-flask
  labels:
    app: lego-apps
spec:
  type: LoadBalancer  # Change to NodePort or ClusterIP based on your cluster setup
  ports:
  - port: 80
    targetPort: 5003
    protocol: TCP
    name: flask
  selector:
    app: lego-apps

